### ISSUE TITLE
Failed to set gamma table

### ISSUE THREAD

**Issue by lilithium-hydride** [mischw/wl-gammactl#9]
When I attempt to run any `wl-gammactl` commands, it just says that it `failed to set gamma table`, rather than setting the specified gamma value. There's no `--verbose` flag as far as I can tell, so I'm afraid I can't provide any other error information. I'm using the same software setup on another device and have no issues there.

**System Details**
* OS: `Artix Linux rolling`
* WM: `Sway 1.6.1`
* Drivers: `NVIDIA Proprietary 495,44`
*The new NVIDIA drivers work fine with Sway, although my other (working) device runs Sway off of AMD integrated graphics. Not sure if this is the source of the issue, though.*

**Comment by lilithium-hydride** [comment]
Closing, as this issue also exists within [https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/examples/gamma-control.c](the official wlroots example.).

**Comment by Lassebq** [comment]
Is there any solution though? I'm getting the same issue and I cannot find any other gamma control utility which works

**Comment by nalply** [comment]
> Closing, as this issue also exists within [the official wlroots example](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/examples/gamma-control.c).

And this example got removed...
